// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"

	"github.com/fledsbo/gobrew/hwinterface"
)

type Batch struct {
	Name         string        `json:"name"`
	State        BatchState    `json:"state"`
	Fermentation *Fermentation `json:"fermentation"`
}

type Fermentation struct {
	Monitor   *hwinterface.MonitorState `json:"monitor"`
	Container *FermentationContainer    `json:"container"`
}

type FermentationContainer struct {
	Name    string `json:"name"`
	CanHeat bool   `json:"canHeat"`
	Heating bool   `json:"heating"`
	Cooling bool   `json:"cooling"`
	CanCool bool   `json:"canCool"`
}

type SetMonitorInput struct {
	Name        string   `json:"name"`
	Temperature *float64 `json:"temperature"`
	Gravity     *float64 `json:"gravity"`
}

type BatchState string

const (
	BatchStatePlanning     BatchState = "PLANNING"
	BatchStateMashing      BatchState = "MASHING"
	BatchStateFermenting   BatchState = "FERMENTING"
	BatchStateConditioning BatchState = "CONDITIONING"
)

var AllBatchState = []BatchState{
	BatchStatePlanning,
	BatchStateMashing,
	BatchStateFermenting,
	BatchStateConditioning,
}

func (e BatchState) IsValid() bool {
	switch e {
	case BatchStatePlanning, BatchStateMashing, BatchStateFermenting, BatchStateConditioning:
		return true
	}
	return false
}

func (e BatchState) String() string {
	return string(e)
}

func (e *BatchState) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BatchState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BatchState", str)
	}
	return nil
}

func (e BatchState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
